### PR TITLE
initial implementation

### PR DESCRIPTION
**Pull request by shahriar-shojib**
wip

### CODE REVIEW

**Comment by kymppi** [comment]
Could you move the code to a directory like `novu` because then there could be a `examples` folder on the root

**Comment by kymppi** [comment]
Hey, could this be merged so i can continue working on it? @scopsy

**Comment by scopsy** [comment]
Thank you so much @shahriar-shojib I'm merging this initial content so we can continue iterating on this one. ❤️

**Review by scopsy — APPROVED** [review]

**Comment by scopsy** [comment]
@kymppi merged it!

**Pull request merged**
